name: Deploy branch documentation

on:
  push:
    branches:
      - xas-modes-choice
      - xas-using-inheritance
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip setuptools
          make install

      - name: Build Documentation
        run: |
          make local

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/manual/build/html
          target-folder: ${{ github.ref_name }}
          clean: true
          clean-exclude: |
            xas-modes-choice
            xas-using-inheritance
